<?php
if (!isset($this->noLayout)):
    echo $this->partial('partials/title.phtml', array(
        'title' => $this->model->getOption('title')
    ));
endif;
?>
<div id="ClientesTabs">
    <ul>
        <li><a href="#Dados">Dados</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Clientes-Enderecos/cliente//<?php echo $this->data['id']; ?>">End.</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Clientes-Telefones/cliente//<?php echo $this->data['id']; ?>">Tel.</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Orcamentos/cliente//<?php echo $this->data['id']; ?>">Orçamentos</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Ordens-Servico/cliente//<?php echo $this->data['id']; ?>">Ordens de Serviço</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Contas-Receber/cliente//<?php echo $this->data['id']; ?>">Faturas</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Notas-Fiscais/cliente//<?php echo $this->data['id']; ?>">N.F.</a></li>
    </ul>
    <div id="Dados">
        <div class="grid_12">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        $("#ClientesTabs").tabs({
            spinner: carregando,
            ajaxOptions: {
                error: function(xhr, status,index, anchor){
                    if(status == 'error'){
                        $(anchor.hash).html('Erro ao carregar o conteúdo');
                    }else{
                        $(anchor.hash).html(carregando);
                    }
                }
            }
<?php echo (empty($this->data['id'])) ? ', disabled: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]' : ''; ?>
        });
<?php if ((isset($this->data['documento_tipo']) && $this->data['documento_tipo'] == 2)): ?>
            $("#documento").unmask();
            $("#documento").mask("999.999.999-99");
<?php else: ?>
            $("#documento").unmask();
            $("#documento").mask("99.999.999/9999-99");
<?php endif; ?>
        $("#documento_tipo").change(function(){
            mudaMascara();
        });
    });
    function mudaMascara(){
        var documento = $("#documento").select().val();
        var selecionado = $("#documento_tipo").select().val();
        if(selecionado == 2){
            $("#documento").unmask();
            $("#documento").mask("999.999.999-99");
            $("#documento").val(documento);
        }else{
            $("#documento").unmask();
            $("#documento").mask("99.999.999/9999-99");
            $("#documento").val(documento);
        }
    }

</script>
