<!DOCTYPE html>
<html>
    <head lang="pt-br">
        <title>Construções JC</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="css/reset.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="css/style.css" media="screen" rel="stylesheet" type="text/css" >
        <meta name="google-site-verification" content="IVfydHukFqenp33xQAuFB_C4tAcQ3JnixixWyiZ_LQY" />
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-26474804-1']);
            _gaq.push(['_trackPageview']);
            (function() {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        <div id="center">
            <p>Contruções JC</p>
            <p>Jair Canegoski</p>
            <p>Fone: (54) 8121.7779</p>
        </div>
    </body>
</html>
