<h1>Fale Conosco</h1>
<div class="borda-cinza borda" id="fale-conosco">
    <div class="column2 margem-r">
        <h2>Localização</h2>
        <div id="mapa_canvas"></div>
    </div>
    <div class="column">
        <h2>Entre em contato por e-mail</h2>
        <?php echo $this->form; ?>
    </div>
</div>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"> </script>
<script type="text/javascript">
    function carregaMapa(){
        var latLang = new google.maps.LatLng(-29.17160, -51.51691);
        var Options = {
            zoom: 16,
            center: latLang,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById('mapa_canvas'), Options);

        var marker = new google.maps.Marker({
            position: latLang,
            map: map,
            title: 'Acquasana - Tratamento de Efluentes',
            clickable: false
        });

    }
    google.maps.event.addDomListener(window, 'load', carregaMapa);
</script>
<style>
    #mapa_canvas{
        width: 615px;
        height: 415px;
    }
</style>