<?php
$configs = Zend_Registry::get('application');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" xml:lang="pt-br">
    <head>
        <?php
        if (isset($this->model)):
            $this->headTitle($this->model->getOption('title'));
        endif;
        $this->headTitle('ERP - '.$configs->cliente->nome);
        $this->headTitle()->setSeparator(' - ');
        echo $this->headTitle();

        /* Adiciona as Meta Tags */
        $this->headMeta()
                ->appendHttpEquiv('Content-Type', 'text/html;charset=UTF-8')
                ->appendHttpEquiv('Content-Language', 'pt-BR')
                ->appendName('author', 'Fernando Henrique - Webscientist')
                ->appendName('robots', 'index,follow')
                ->appendName('googlebot', 'index,follow')
                ->appendName('google', 'notranslate')
                ->appendName('Content-Language', 'pt-br')
                ->appendName('reply-to', $configs->cliente->email)
                ->appendName('google-site-verification', $configs->google->verification);
        echo $this->headMeta();

        $this->headLink()
                ->appendStylesheet('/css/light/jquery-ui-1.8.23.custom.css')
                ->appendStylesheet('/css/impressao.css', 'all')
                ->appendStylesheet('/css/print.css', 'print')
                ->headLink(array('rel' => 'favicon', 'href' => '/favicon.ico'), 'PREPEND')
                ->headLink(array('rel' => 'shortcut icon', 'href' => '/favicon.ico', 'type' => 'image/x-icon'), 'PREPEND');
        echo $this->headLink();

        $this->headScript()
                ->appendFile('/js/jquery-1.8.0.min.js')
                ->appendFile('/js/jquery-ui-1.8.23.custom.min.js')
                ->appendFile('/js/script.js')
                ->appendFile('/js/jquery.maskMoney.js')
                ->appendFile('/js/jquery.maskedinput-1.3.min.js')
                ->appendFile('/js/jquery.livequery.js')
                ->appendFile('/js/jquery.form.js')
                ->appendFile('https://www.google.com/jsapi')
        ;
        echo $this->headScript();
        ?>
    </head>
    <body>
        <?php if (!isset($this->noLogo)): ?>
            <div id="logo" class="center">
                <a href="/erp"><img src="/images/logo.jpg" border="0" /></a>
            </div>
        <?php endif; ?>
        <?php echo $this->layout()->content; ?>
    </body>
</html>