<h2>Relatório de Fluxo de Caixa</h2>
<form method="POST">
    <table class="listagem hidden margemB">
        <tr>
            <th colspan="4">Data inicial</th>
            <th colspan="4">Data final</th>
            <th rowspan="2"><button type="submit">Filtrar</button></th>
            <th rowspan="2"><button type="button" id="btImprimir">Imprimir</button></th>
        </tr>
        <tr>
            <th>Mês</th>
            <th><select name="dataInicial[mes]" class="ui-corner-all mes">
                    <?php for ($i = 1; $i < 13; $i++):?>
                        <option value="<?php echo substr('0' . $i, -2); ?>" <?php echo ($this->data['dataInicial']['mes'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </th>
            <th>Ano</th>
            <th><select name="dataInicial[ano]" class="ui-corner-all filter ano">
                    <?php for ($i = 2000; $i <= 2020; $i++): ?>
                        <option value="<?php echo $i; ?>" <?php echo ($this->data['dataInicial']['ano'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </th>
            <th>Mês</th>
            <th><select name="dataFinal[mes]" class="ui-corner-all mes">
                    <?php for ($i = 1; $i < 13; $i++): ?>
                        <option value="<?php echo substr('0' . $i, -2); ?>" <?php echo ($this->data['dataFinal']['mes'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </th>
            <th>Ano</th>
            <th><select name="dataFinal[ano]" class="ui-corner-all filtro ano">
                    <?php for ($i = 2000; $i <= 2020; $i++): ?>
                        <option value="<?php echo $i; ?>" <?php echo ($this->data['dataFinal']['ano'] == $i) ? 'selected="selected"' : ''; ?>><?php echo $i; ?></option>
                    <?php endfor; ?>
                </select>
            </th>
        </tr>
    </table>
</form>
<?php
if (!empty($this->contas)):
    $WM = new WS_Money();
    $periodoInicial = new Zend_Date($this->data['dataInicial']['ano'] . '-' . $this->data['dataInicial']['mes'] . '-01');
    $periodoFinal = new Zend_Date($this->data['dataFinal']['ano'] . '-' . $this->data['dataFinal']['mes'] . '-01');
    ?>
    <h2>Período Apurado [<?php echo $periodoInicial->toString('MM/yyyy') . ' - ' . $periodoFinal->toString('MM/yyyy'); ?>]</h2>
    <div id="grafico" style="width: 700px; margin:0 auto;"></div>
    <table class="listagem">
        <thead>
            <tr>
                <td>Mês/Ano</td>
                <th>Recebido</th>
                <th>Pago</th>
                <th>Saldo</th>
                <th>Faturamento (<?php echo WS_Money::adjustToView($this->saldoAcumulado); ?>)</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $total = array('recebido' => 0, 'pago' => 0, 'saldo' => 0);
            foreach ($this->contas AS $conta):
                $saldo = $conta['contas_receber'] - $conta['contas_pagar'];
                $total['recebido'] += $conta['contas_receber'];
                $total['pago'] += $conta['contas_pagar'];
                $total['saldo'] += $conta['saldo'];
                ?>
                <tr>
                    <th><?php echo $conta['legenda']; ?></th>
                    <td class="valor"><?php echo WS_Money::adjustToView($conta['contas_receber']); ?></td>
                    <td class="valor"><?php echo WS_Money::adjustToView($conta['contas_pagar']); ?></td>
                    <td class="valor"><?php echo WS_Money::adjustToView($conta['saldo']); ?></td>
                    <td class="valor"><?php echo WS_Money::adjustToView($conta['acumulado']); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <th>Total</th>
                <th><?php echo WS_Money::adjustToView($total['recebido']); ?></th>
                <th><?php echo WS_Money::adjustToView($total['pago']); ?></th>
                <th><?php echo WS_Money::adjustToView($total['saldo']); ?></th>
                <th></th>
            </tr>
        </tfoot>
    </table>
    <?php
    if (!empty($this->contasCategorizadas)):
        $total = array('liquido' => $total['recebido'], 'saldo' => $total['recebido']);
        ?>
        <br class="clear margemB" />
        <h2>Detalhamento por categoria</h2>
        <table class="listagem">
            <thead>
            <th>Categoria de Conta</th>
            <th>% do Faturamento</th>
            <th>Total</th>
            <th>Recebido (<?php echo WS_Money::adjustToView($total['saldo']); ?>)</th>
        </thead>
        <tbody>
            <?php
            foreach ($this->contasCategorizadas AS $conta):
                $porcentagem = $conta['total'] * 100 / $total['liquido'];
                $total['saldo'] -= $conta['total'];
                ?>
                <tr>
                    <td><?php echo $conta['categoria']; ?></td>
                    <td align="center"><?php echo WS_Money::adjustToDb($porcentagem); ?>%</td>
                    <td><?php echo WS_Money::adjustToView($conta['total']); ?></td>
                    <td><?php echo WS_Money::adjustToView($total['saldo']); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        </table>
    <?php endif; ?>
    <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Ano');
            data.addColumn('number', 'Recebido');
            data.addColumn('number', 'Pago');
            data.addRows([
    <?php foreach ($this->contas AS $conta): ?>
                    ['<?php echo $conta['legenda']; ?>', <?php echo $conta['contas_receber']; ?>, <?php echo $conta['contas_pagar']; ?>],
    <?php endforeach; ?>
            ]);

            var chart = new google.visualization.ColumnChart(document.getElementById('grafico'));
            chart.draw(data, {width: 700, height: 400, title: 'Fluxo de Caixa', colors: ['green','red'],
                hAxis: {title: 'Ano'}, vAxis: {title: 'Valor'}

            });
        }
    </script>
<?php else: ?>
    <div class="empty">
        Nenhum dado filtrado
    </div>
<?php endif; ?>